### ISSUE TITLE
missing keys after regen

### ISSUE THREAD

**Issue by rurban** [perl11/p5-Config#3] opened 2015-12-25 23:56 UTC
See http://paste.scsys.co.uk/503478

Those missing keys do exist in config.sh and Config_heavy.
And ideally there should be a test that regen does not loose keys.
See also https://github.com/perl11/cperl/issues/99

**Comment by bulk88** [comment] 2015-12-27 00:00
Not loosing keys is covered by the existing XSConfig.t test, it failed as designed in https://travis-ci.org/perl11/cperl/jobs/98823118#L4632 https://travis-ci.org/perl11/cperl/jobs/98823118#L6512 after your "make regen" with wrong perl build/branch. I am closing this ticket since there is nothing more to do in it since XSConfig.t did catch the lost keys for that CI build.

**Closed as completed by bulk88** 2015-12-27 00:00 UTC
